import { KeyTakeaway } from '@/components/content/KeyTakeaway';
import { KnowledgeCheck } from '@/components/content/KnowledgeCheck';
import { Term } from '@/components/content/Term';
import { defineLesson } from '@/lib/sections';

const DOCUMENTS = [
  { name: 'NEP', role: 'Proposal', description: 'The executive branch presents its proposed spending plan to Congress for deliberation.' },
  { name: 'GAA', role: 'Enacted authority', description: 'After legislation and presidential action, the appropriations law authorizes spending for stated purposes and within stated limits.' },
  { name: 'Execution reports', role: 'What happened next', description: 'Release, obligation, disbursement, and accomplishment records show how agencies carried out the enacted budget.' },
];

export default defineLesson({
  sections: [
    { id: 'start', title: 'Three books, three different questions', shortTitle: 'Start', type: 'introduction', content: <><p className="text-lg text-muted-foreground">If the national budget were a library, which book would you open to find the executive proposal, the amount Congress approved, or the plan for financing the whole budget?</p><p>Budget documents can contain similar labels and tables, but they do not have the same legal status or answer the same questions. Start by checking the document title and fiscal year before reading any amount.</p></> },
    { id: 'three-documents', title: 'Meet the three core documents', shortTitle: 'Three documents', type: 'concept', content: <><p>The <Term id="nep" expand /> is the President&apos;s proposed national budget submitted to Congress. It shows what the executive branch is asking the legislature to authorize.</p><p>The <Term id="gaa" expand /> is the enacted appropriations law. It is the document to consult when your question is what spending Congress authorized after the legislative process and presidential action.</p><p>The <Term id="besf" expand /> places the expenditure program beside the sources of financing that support it. It also provides the fiscal and macroeconomic context for the national budget proposal.</p></> },
    { id: 'lifecycle', title: 'How the documents fit together', shortTitle: 'Lifecycle', type: 'example', content: <><p>Read the NEP and GAA as two points in a sequence. The first is a proposal; the second is the authority enacted after Congress considers that proposal. Execution reports come later and answer a different question: what happened to the authority after enactment?</p><div className="not-prose my-8 grid gap-3 md:grid-cols-[1fr_auto_1fr_auto_1fr] md:items-stretch" aria-label="National budget document lifecycle">{DOCUMENTS.map((document, index) => <div key={document.name} className="contents"><div className="rounded-lg border bg-card p-5"><p className="text-xs font-semibold uppercase tracking-wide text-primary">{document.role}</p><h3 className="mt-1 font-semibold">{document.name}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{document.description}</p></div>{index < DOCUMENTS.length - 1 && <div className="flex items-center justify-center text-xl text-primary" aria-hidden="true"><span className="md:hidden">↓</span><span className="hidden md:inline">→</span></div>}</div>)}</div><p>The BESF sits alongside the proposal rather than replacing a step in this sequence. It explains the wider fiscal program: expected expenditures, revenues, borrowing, and other financing information that frame the proposed budget.</p></> },
    { id: 'choose-the-document', title: 'Choose by question, not by familiarity', shortTitle: 'Choose', type: 'concept', content: <><ul><li><strong>What did the executive propose?</strong> Start with the NEP.</li><li><strong>What spending was enacted?</strong> Start with the GAA.</li><li><strong>How do expenditures relate to revenues and financing?</strong> Start with the BESF.</li><li><strong>Was the enacted amount released, committed, paid, or delivered?</strong> Move beyond these three documents to the relevant execution or accomplishment report.</li></ul><p>A figure in the NEP may change during legislation. A figure in the GAA is an authorization, not proof that the agency received, paid, or delivered the full amount. Naming the document prevents those stages from being mixed together.</p><p className="text-sm text-muted-foreground">Source note: Department of Budget and Management descriptions of the <a href="https://www.dbm.gov.ph/index.php/budget-documents/2025/national-expenditure-program-fy-2025">National Expenditure Program</a> and <a href="https://www.dbm.gov.ph/index.php/test/1205-budget-of-expenditures-and-sources-of-financing">Budget of Expenditures and Sources of Financing</a>.</p></> },
    { id: 'check', title: 'Check your understanding', shortTitle: 'Check', type: 'knowledge-check', content: <KnowledgeCheck title="Pick the document that best answers each question" moduleId="mod-03" lessonId="03.1" items={[{ prompt: 'How much did Congress authorize for a national government program?', options: ['National Expenditure Program', 'General Appropriations Act', 'Budget of Expenditures and Sources of Financing'], correct: 1, explanation: 'The GAA is the enacted appropriations law, so it is the starting document for an amount Congress authorized.', wrong: { 0: 'The NEP shows the executive proposal before Congress completes legislation; the proposed amount may change.', 2: 'The BESF explains the expenditure and financing program, but the GAA is the enacted authority for this question.' } }, { prompt: 'What amount did the executive branch originally propose for a program?', options: ['National Expenditure Program', 'General Appropriations Act', 'An execution report'], correct: 0, explanation: 'The NEP records the executive branch proposal submitted to Congress.', wrong: { 1: "The GAA reflects the enacted result after legislation, not necessarily the executive branch's original proposal.", 2: 'Execution reports track what happens after enactment; they do not state the original proposal.' } }, { prompt: 'Which document best shows estimated expenditures together with their sources of financing?', options: ['General Appropriations Act', 'Budget of Expenditures and Sources of Financing', 'An agency accomplishment report'], correct: 1, explanation: 'The BESF presents the expenditure program and the revenue, borrowing, and other financing context that supports it.', wrong: { 0: 'The GAA grants spending authority, but this question asks for the wider expenditure-and-financing picture.', 2: 'An accomplishment report focuses on implementation results rather than the government-wide financing plan.' } }]} /> },
    { id: 'takeaway', title: 'Key takeaway', shortTitle: 'Takeaway', type: 'takeaway', content: <KeyTakeaway>Match the document to the question: the <Term id="nep" /> is the executive proposal, the <Term id="gaa" /> is the enacted spending authority, and the <Term id="besf" /> explains expenditures and their financing in a wider fiscal picture. None, by itself, proves that a service was delivered.</KeyTakeaway> },
  ],
});
